import type { Metadata } from "next";
import { Ga4Consent } from "@/components/analytics/ga4-consent";
import { siteUrl } from "@/lib/seo/site";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: siteUrl,
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        {children}
        <Ga4Consent
          measurementId={process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID}
        />
      </body>
    </html>
  );
}
