export type ProductGalleryImageType =
  | "front"
  | "side"
  | "back"
  | "detail"
  | "interface"
  | "application";

export type ProductGalleryImage = {
  src: string;
  thumbnailSrc: string;
  width: number;
  height: number;
  alt: string;
  type: ProductGalleryImageType;
};
export type ProductGallery = {
  featuredImage: Omit<ProductGalleryImage, "type">;
  gallery: ProductGalleryImage[];
};

export const productGalleries: Record<string, ProductGallery> = {
  "86-type-ai-smart-control-display": {
    featuredImage: {
      src: "/media/products/86-type-ai-smart-control-display/hero.webp",
      thumbnailSrc: "/media/products/86-type-ai-smart-control-display/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "86-Type AI Smart Control Display",
    },
    gallery: [
      {
        src: "/media/products/86-type-ai-smart-control-display/interface-01.webp",
        thumbnailSrc: "/media/products/86-type-ai-smart-control-display/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "86-Type AI Smart Control Display interface detail",
        type: "interface",
      },
      {
        src: "/media/products/86-type-ai-smart-control-display/detail-01.webp",
        thumbnailSrc: "/media/products/86-type-ai-smart-control-display/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "86-Type AI Smart Control Display product detail",
        type: "detail",
      },
      {
        src: "/media/products/86-type-ai-smart-control-display/side-01.webp",
        thumbnailSrc: "/media/products/86-type-ai-smart-control-display/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "86-Type AI Smart Control Display side view",
        type: "side",
      },
      {
        src: "/media/products/86-type-ai-smart-control-display/application-01.webp",
        thumbnailSrc: "/media/products/86-type-ai-smart-control-display/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "86-Type AI Smart Control Display application view",
        type: "application",
      },
    ],
  },
  "ai-large-smart-display": {
    featuredImage: {
      src: "/media/products/ai-large-smart-display/hero.webp",
      thumbnailSrc: "/media/products/ai-large-smart-display/thumb/hero.webp",
      width: 1200,
      height: 441,
      alt: "AI Large Smart Display",
    },
    gallery: [
      {
        src: "/media/products/ai-large-smart-display/detail-01.webp",
        thumbnailSrc: "/media/products/ai-large-smart-display/thumb/detail-01.webp",
        width: 786,
        height: 1600,
        alt: "AI Large Smart Display product detail",
        type: "detail",
      },
      {
        src: "/media/products/ai-large-smart-display/interface-01.webp",
        thumbnailSrc: "/media/products/ai-large-smart-display/thumb/interface-01.webp",
        width: 1600,
        height: 1577,
        alt: "AI Large Smart Display interface detail",
        type: "interface",
      },
    ],
  },
  "ai-music-control-panel": {
    featuredImage: {
      src: "/media/products/ai-music-control-panel/hero.webp",
      thumbnailSrc: "/media/products/ai-music-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "AI Music Control Panel",
    },
    gallery: [
      {
        src: "/media/products/ai-music-control-panel/interface-01.webp",
        thumbnailSrc: "/media/products/ai-music-control-panel/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "AI Music Control Panel interface detail 1",
        type: "interface",
      },
      {
        src: "/media/products/ai-music-control-panel/interface-02.webp",
        thumbnailSrc: "/media/products/ai-music-control-panel/thumb/interface-02.webp",
        width: 1600,
        height: 1066,
        alt: "AI Music Control Panel interface detail 2",
        type: "interface",
      },
      {
        src: "/media/products/ai-music-control-panel/detail-01.webp",
        thumbnailSrc: "/media/products/ai-music-control-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "AI Music Control Panel product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/ai-music-control-panel/detail-02.webp",
        thumbnailSrc: "/media/products/ai-music-control-panel/thumb/detail-02.webp",
        width: 500,
        height: 503,
        alt: "AI Music Control Panel product detail 2",
        type: "detail",
      },
    ],
  },
  "borui-red-matte-room-status-four-key-switch-panel": {
    featuredImage: {
      src: "/media/products/borui-red-matte-room-status-four-key-switch-panel/hero.webp",
      thumbnailSrc: "/media/products/borui-red-matte-room-status-four-key-switch-panel/thumb/hero.webp",
      width: 1200,
      height: 595,
      alt: "Borui Red Matte Room Status and Four-Key Switch Panel",
    },
    gallery: [
      {
        src: "/media/products/borui-red-matte-room-status-four-key-switch-panel/side-01.webp",
        thumbnailSrc: "/media/products/borui-red-matte-room-status-four-key-switch-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Borui Red Matte Room Status and Four-Key Switch Panel side view",
        type: "side",
      },
      {
        src: "/media/products/borui-red-matte-room-status-four-key-switch-panel/back-01.webp",
        thumbnailSrc: "/media/products/borui-red-matte-room-status-four-key-switch-panel/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Borui Red Matte Room Status and Four-Key Switch Panel back view",
        type: "back",
      },
    ],
  },
  "borui-red-matte-triple-socket-panel": {
    featuredImage: {
      src: "/media/products/borui-red-matte-triple-socket-panel/hero.webp",
      thumbnailSrc: "/media/products/borui-red-matte-triple-socket-panel/thumb/hero.webp",
      width: 1200,
      height: 401,
      alt: "Borui Red Matte Triple Socket Panel",
    },
    gallery: [
      {
        src: "/media/products/borui-red-matte-triple-socket-panel/side-01.webp",
        thumbnailSrc: "/media/products/borui-red-matte-triple-socket-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Borui Red Matte Triple Socket Panel side view",
        type: "side",
      },
    ],
  },
  "borui-red-matte-usb-five-hole-socket": {
    featuredImage: {
      src: "/media/products/borui-red-matte-usb-five-hole-socket/hero.webp",
      thumbnailSrc: "/media/products/borui-red-matte-usb-five-hole-socket/thumb/hero.webp",
      width: 1197,
      height: 1200,
      alt: "Borui Red Matte USB Five-Hole Socket",
    },
    gallery: [
      {
        src: "/media/products/borui-red-matte-usb-five-hole-socket/side-01.webp",
        thumbnailSrc: "/media/products/borui-red-matte-usb-five-hole-socket/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Borui Red Matte USB Five-Hole Socket side view",
        type: "side",
      },
      {
        src: "/media/products/borui-red-matte-usb-five-hole-socket/back-01.webp",
        thumbnailSrc: "/media/products/borui-red-matte-usb-five-hole-socket/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Borui Red Matte USB Five-Hole Socket back view",
        type: "back",
      },
    ],
  },
  "brushed-aluminum-86-base-doorbell-panel": {
    featuredImage: {
      src: "/media/products/brushed-aluminum-86-base-doorbell-panel/hero.webp",
      thumbnailSrc: "/media/products/brushed-aluminum-86-base-doorbell-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Brushed Aluminum 86-Base Doorbell Panel",
    },
    gallery: [
      {
        src: "/media/products/brushed-aluminum-86-base-doorbell-panel/detail-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-86-base-doorbell-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum 86-Base Doorbell Panel product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/brushed-aluminum-86-base-doorbell-panel/detail-02.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-86-base-doorbell-panel/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum 86-Base Doorbell Panel product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/brushed-aluminum-86-base-doorbell-panel/detail-03.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-86-base-doorbell-panel/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum 86-Base Doorbell Panel product detail 3",
        type: "detail",
      },
      {
        src: "/media/products/brushed-aluminum-86-base-doorbell-panel/application-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-86-base-doorbell-panel/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum 86-Base Doorbell Panel application view",
        type: "application",
      },
    ],
  },
  "brushed-aluminum-sos-alarm-panel": {
    featuredImage: {
      src: "/media/products/brushed-aluminum-sos-alarm-panel/hero.webp",
      thumbnailSrc: "/media/products/brushed-aluminum-sos-alarm-panel/thumb/hero.webp",
      width: 1200,
      height: 1194,
      alt: "Brushed Aluminum SOS Alarm Panel",
    },
    gallery: [
      {
        src: "/media/products/brushed-aluminum-sos-alarm-panel/side-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-sos-alarm-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum SOS Alarm Panel side view",
        type: "side",
      },
      {
        src: "/media/products/brushed-aluminum-sos-alarm-panel/detail-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-sos-alarm-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum SOS Alarm Panel product detail",
        type: "detail",
      },
      {
        src: "/media/products/brushed-aluminum-sos-alarm-panel/back-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-sos-alarm-panel/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum SOS Alarm Panel back view",
        type: "back",
      },
    ],
  },
  "brushed-aluminum-thermostat-control-panel": {
    featuredImage: {
      src: "/media/products/brushed-aluminum-thermostat-control-panel/hero.webp",
      thumbnailSrc: "/media/products/brushed-aluminum-thermostat-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Brushed Aluminum Thermostat Control Panel",
    },
    gallery: [
      {
        src: "/media/products/brushed-aluminum-thermostat-control-panel/side-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-thermostat-control-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum Thermostat Control Panel side view",
        type: "side",
      },
      {
        src: "/media/products/brushed-aluminum-thermostat-control-panel/detail-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-thermostat-control-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum Thermostat Control Panel product detail",
        type: "detail",
      },
      {
        src: "/media/products/brushed-aluminum-thermostat-control-panel/back-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-thermostat-control-panel/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum Thermostat Control Panel back view",
        type: "back",
      },
    ],
  },
  "brushed-aluminum-voice-telephone-information-panel": {
    featuredImage: {
      src: "/media/products/brushed-aluminum-voice-telephone-information-panel/hero.webp",
      thumbnailSrc: "/media/products/brushed-aluminum-voice-telephone-information-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Brushed Aluminum Voice and Telephone Information Panel",
    },
    gallery: [
      {
        src: "/media/products/brushed-aluminum-voice-telephone-information-panel/side-01.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-voice-telephone-information-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum Voice and Telephone Information Panel side view 1",
        type: "side",
      },
      {
        src: "/media/products/brushed-aluminum-voice-telephone-information-panel/side-02.webp",
        thumbnailSrc: "/media/products/brushed-aluminum-voice-telephone-information-panel/thumb/side-02.webp",
        width: 1600,
        height: 1066,
        alt: "Brushed Aluminum Voice and Telephone Information Panel side view 2",
        type: "side",
      },
    ],
  },
  "embedded-human-presence-sensor": {
    featuredImage: {
      src: "/media/products/embedded-human-presence-sensor/detail-01.webp",
      thumbnailSrc: "/media/products/embedded-human-presence-sensor/thumb/detail-01.webp",
      width: 1600,
      height: 1066,
      alt: "Embedded Human Presence Sensor front view",
    },
    gallery: [
      {
        src: "/media/products/embedded-human-presence-sensor/detail-02.webp",
        thumbnailSrc: "/media/products/embedded-human-presence-sensor/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Embedded Human Presence Sensor angled front view",
        type: "side",
      },
      {
        src: "/media/products/embedded-human-presence-sensor/application-01.webp",
        thumbnailSrc: "/media/products/embedded-human-presence-sensor/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "Embedded Human Presence Sensor alternate side view",
        type: "side",
      },
      {
        src: "/media/products/embedded-human-presence-sensor/hero.webp",
        thumbnailSrc: "/media/products/embedded-human-presence-sensor/thumb/hero.webp",
        width: 1200,
        height: 800,
        alt: "Embedded Human Presence Sensor side and terminal view",
        type: "back",
      },
      {
        src: "/media/products/embedded-human-presence-sensor/detail-03.webp",
        thumbnailSrc: "/media/products/embedded-human-presence-sensor/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Embedded Human Presence Sensor rear terminal detail",
        type: "interface",
      },
    ],
  },
  "hotel-ceiling-background-speaker": {
    featuredImage: {
      src: "/media/products/hotel-ceiling-background-speaker/hero.webp",
      thumbnailSrc: "/media/products/hotel-ceiling-background-speaker/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Ceiling Background Speaker",
    },
    gallery: [
      {
        src: "/media/products/hotel-ceiling-background-speaker/front-01.webp",
        thumbnailSrc: "/media/products/hotel-ceiling-background-speaker/thumb/front-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Ceiling Background Speaker front view 1",
        type: "front",
      },
      {
        src: "/media/products/hotel-ceiling-background-speaker/front-02.webp",
        thumbnailSrc: "/media/products/hotel-ceiling-background-speaker/thumb/front-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Ceiling Background Speaker front view 2",
        type: "front",
      },
    ],
  },
  "hotel-delivery-robot": {
    featuredImage: {
      src: "/media/products/hotel-delivery-robot/application-01.webp",
      thumbnailSrc: "/media/products/hotel-delivery-robot/thumb/application-01.webp",
      width: 1066,
      height: 1600,
      alt: "Hotel Delivery Robot front view",
    },
    gallery: [
      {
        src: "/media/products/hotel-delivery-robot/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot three-quarter view",
        type: "side",
      },
      {
        src: "/media/products/hotel-delivery-robot/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot/thumb/detail-01.webp",
        width: 1066,
        height: 1600,
        alt: "Hotel Delivery Robot rear view",
        type: "back",
      },
      {
        src: "/media/products/hotel-delivery-robot/interface-01.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot upper control interface",
        type: "interface",
      },
      {
        src: "/media/products/hotel-delivery-robot/hero.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot/thumb/hero.webp",
        width: 1200,
        height: 800,
        alt: "Hotel Delivery Robot control display close-up",
        type: "interface",
      },
    ],
  },
  "hotel-delivery-robot-charging-dock": {
    featuredImage: {
      src: "/media/products/hotel-delivery-robot-charging-dock/hero.webp",
      thumbnailSrc: "/media/products/hotel-delivery-robot-charging-dock/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Delivery Robot Charging Dock",
    },
    gallery: [
      {
        src: "/media/products/hotel-delivery-robot-charging-dock/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot-charging-dock/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot Charging Dock product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/hotel-delivery-robot-charging-dock/side-01.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot-charging-dock/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot Charging Dock side view",
        type: "side",
      },
      {
        src: "/media/products/hotel-delivery-robot-charging-dock/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot-charging-dock/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot Charging Dock product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/hotel-delivery-robot-charging-dock/detail-03.webp",
        thumbnailSrc: "/media/products/hotel-delivery-robot-charging-dock/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Delivery Robot Charging Dock product detail 3",
        type: "detail",
      },
    ],
  },
  "hotel-guest-room-doorbell": {
    featuredImage: {
      src: "/media/products/hotel-guest-room-doorbell/hero.webp",
      thumbnailSrc: "/media/products/hotel-guest-room-doorbell/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Guest Room Doorbell",
    },
    gallery: [
      {
        src: "/media/products/hotel-guest-room-doorbell/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-guest-room-doorbell/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Guest Room Doorbell product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/hotel-guest-room-doorbell/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-guest-room-doorbell/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Guest Room Doorbell product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/hotel-guest-room-doorbell/detail-03.webp",
        thumbnailSrc: "/media/products/hotel-guest-room-doorbell/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Guest Room Doorbell product detail 3",
        type: "detail",
      },
    ],
  },
  "hotel-room-door-magnetic-sensor": {
    featuredImage: {
      src: "/media/products/hotel-room-door-magnetic-sensor/hero.webp",
      thumbnailSrc: "/media/products/hotel-room-door-magnetic-sensor/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Room Door Magnetic Sensor",
    },
    gallery: [
      {
        src: "/media/products/hotel-room-door-magnetic-sensor/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-room-door-magnetic-sensor/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Room Door Magnetic Sensor product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/hotel-room-door-magnetic-sensor/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-room-door-magnetic-sensor/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Room Door Magnetic Sensor product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/hotel-room-door-magnetic-sensor/detail-03.webp",
        thumbnailSrc: "/media/products/hotel-room-door-magnetic-sensor/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Room Door Magnetic Sensor product detail 3",
        type: "detail",
      },
      {
        src: "/media/products/hotel-room-door-magnetic-sensor/application-01.webp",
        thumbnailSrc: "/media/products/hotel-room-door-magnetic-sensor/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Room Door Magnetic Sensor application view",
        type: "application",
      },
    ],
  },
  "hotel-smart-delivery-cabinet": {
    featuredImage: {
      src: "/media/products/hotel-smart-delivery-cabinet/hero.webp",
      thumbnailSrc: "/media/products/hotel-smart-delivery-cabinet/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Smart Delivery Cabinet",
    },
    gallery: [
      {
        src: "/media/products/hotel-smart-delivery-cabinet/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-delivery-cabinet/thumb/detail-01.webp",
        width: 1600,
        height: 1067,
        alt: "Hotel Smart Delivery Cabinet product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/hotel-smart-delivery-cabinet/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-smart-delivery-cabinet/thumb/detail-02.webp",
        width: 1600,
        height: 1067,
        alt: "Hotel Smart Delivery Cabinet product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/hotel-smart-delivery-cabinet/application-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-delivery-cabinet/thumb/application-01.webp",
        width: 1600,
        height: 1067,
        alt: "Hotel Smart Delivery Cabinet application view",
        type: "application",
      },
      {
        src: "/media/products/hotel-smart-delivery-cabinet/detail-03.webp",
        thumbnailSrc: "/media/products/hotel-smart-delivery-cabinet/thumb/detail-03.webp",
        width: 1600,
        height: 1067,
        alt: "Hotel Smart Delivery Cabinet product detail 3",
        type: "detail",
      },
    ],
  },
  "hotel-smart-room-rcu-host-1": {
    featuredImage: {
      src: "/media/products/hotel-smart-room-rcu-host-1/hero.webp",
      thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-1/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Smart Room RCU Host 1",
    },
    gallery: [
      {
        src: "/media/products/hotel-smart-room-rcu-host-1/detail-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-1/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Smart Room RCU Host 1 product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/hotel-smart-room-rcu-host-1/detail-02.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-1/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Smart Room RCU Host 1 product detail 2",
        type: "detail",
      },
    ],
  },
  "hotel-smart-room-rcu-host-2": {
    featuredImage: {
      src: "/media/products/hotel-smart-room-rcu-host-2/hero.webp",
      thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-2/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Hotel Smart Room RCU Host 2",
    },
    gallery: [
      {
        src: "/media/products/hotel-smart-room-rcu-host-2/side-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-2/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Smart Room RCU Host 2 side view",
        type: "side",
      },
      {
        src: "/media/products/hotel-smart-room-rcu-host-2/back-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-2/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Hotel Smart Room RCU Host 2 back view",
        type: "back",
      },
    ],
  },
  "hotel-smart-room-rcu-host-3": {
    featuredImage: {
      src: "/media/products/hotel-smart-room-rcu-host-3/hero.webp",
      thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-3/thumb/hero.webp",
      width: 1200,
      height: 676,
      alt: "Hotel Smart Room RCU Host 3",
    },
    gallery: [
      {
        src: "/media/products/hotel-smart-room-rcu-host-3/side-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-3/thumb/side-01.webp",
        width: 1600,
        height: 901,
        alt: "Hotel Smart Room RCU Host 3 side view 1",
        type: "side",
      },
      {
        src: "/media/products/hotel-smart-room-rcu-host-3/side-02.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-3/thumb/side-02.webp",
        width: 1600,
        height: 901,
        alt: "Hotel Smart Room RCU Host 3 side view 2",
        type: "side",
      },
      {
        src: "/media/products/hotel-smart-room-rcu-host-3/back-01.webp",
        thumbnailSrc: "/media/products/hotel-smart-room-rcu-host-3/thumb/back-01.webp",
        width: 1600,
        height: 901,
        alt: "Hotel Smart Room RCU Host 3 back view",
        type: "back",
      },
    ],
  },
  "infrared-repeater": {
    featuredImage: {
      src: "/media/products/infrared-repeater/hero.webp",
      thumbnailSrc: "/media/products/infrared-repeater/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Infrared Repeater",
    },
    gallery: [
      {
        src: "/media/products/infrared-repeater/detail-01.webp",
        thumbnailSrc: "/media/products/infrared-repeater/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Infrared Repeater product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/infrared-repeater/interface-01.webp",
        thumbnailSrc: "/media/products/infrared-repeater/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "Infrared Repeater interface detail",
        type: "interface",
      },
      {
        src: "/media/products/infrared-repeater/detail-02.webp",
        thumbnailSrc: "/media/products/infrared-repeater/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Infrared Repeater product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/infrared-repeater/application-01.webp",
        thumbnailSrc: "/media/products/infrared-repeater/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "Infrared Repeater application view",
        type: "application",
      },
    ],
  },
  "rcu-controller-cabinet": {
    featuredImage: {
      src: "/media/products/rcu-controller-cabinet/hero.webp",
      thumbnailSrc: "/media/products/rcu-controller-cabinet/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "RCU Controller Cabinet",
    },
    gallery: [
      {
        src: "/media/products/rcu-controller-cabinet/detail-01.webp",
        thumbnailSrc: "/media/products/rcu-controller-cabinet/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "RCU Controller Cabinet product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/rcu-controller-cabinet/interface-01.webp",
        thumbnailSrc: "/media/products/rcu-controller-cabinet/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "RCU Controller Cabinet interface detail",
        type: "interface",
      },
      {
        src: "/media/products/rcu-controller-cabinet/detail-02.webp",
        thumbnailSrc: "/media/products/rcu-controller-cabinet/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "RCU Controller Cabinet product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/rcu-controller-cabinet/application-01.webp",
        thumbnailSrc: "/media/products/rcu-controller-cabinet/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "RCU Controller Cabinet application view",
        type: "application",
      },
    ],
  },
  "rotary-knob-smart-control-display": {
    featuredImage: {
      src: "/media/products/rotary-knob-smart-control-display/hero.webp",
      thumbnailSrc: "/media/products/rotary-knob-smart-control-display/thumb/hero.webp",
      width: 1200,
      height: 646,
      alt: "Rotary Knob Smart Control Display",
    },
    gallery: [
    ],
  },
  "smart-curtain-motor": {
    featuredImage: {
      src: "/media/products/smart-curtain-motor/hero.webp",
      thumbnailSrc: "/media/products/smart-curtain-motor/thumb/hero.webp",
      width: 1200,
      height: 1200,
      alt: "Smart Curtain Motor",
    },
    gallery: [
      {
        src: "/media/products/smart-curtain-motor/detail-01.webp",
        thumbnailSrc: "/media/products/smart-curtain-motor/thumb/detail-01.webp",
        width: 1600,
        height: 1000,
        alt: "Smart Curtain Motor product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/smart-curtain-motor/detail-02.webp",
        thumbnailSrc: "/media/products/smart-curtain-motor/thumb/detail-02.webp",
        width: 455,
        height: 1600,
        alt: "Smart Curtain Motor product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/smart-curtain-motor/detail-03.webp",
        thumbnailSrc: "/media/products/smart-curtain-motor/thumb/detail-03.webp",
        width: 1600,
        height: 559,
        alt: "Smart Curtain Motor product detail 3",
        type: "detail",
      },
      {
        src: "/media/products/smart-curtain-motor/detail-04.webp",
        thumbnailSrc: "/media/products/smart-curtain-motor/thumb/detail-04.webp",
        width: 1600,
        height: 1439,
        alt: "Smart Curtain Motor product detail 4",
        type: "detail",
      },
    ],
  },
  "smart-footlight-night-light-panel": {
    featuredImage: {
      src: "/media/products/smart-footlight-night-light-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-footlight-night-light-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Footlight and Night Light Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-footlight-night-light-panel/side-01.webp",
        thumbnailSrc: "/media/products/smart-footlight-night-light-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Footlight and Night Light Panel side view",
        type: "side",
      },
      {
        src: "/media/products/smart-footlight-night-light-panel/back-01.webp",
        thumbnailSrc: "/media/products/smart-footlight-night-light-panel/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Footlight and Night Light Panel back view",
        type: "back",
      },
    ],
  },
  "smart-four-key-curtain-control-panel": {
    featuredImage: {
      src: "/media/products/smart-four-key-curtain-control-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-four-key-curtain-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Four-Key Curtain Control Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-four-key-curtain-control-panel/detail-01.webp",
        thumbnailSrc: "/media/products/smart-four-key-curtain-control-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Four-Key Curtain Control Panel product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/smart-four-key-curtain-control-panel/detail-02.webp",
        thumbnailSrc: "/media/products/smart-four-key-curtain-control-panel/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Four-Key Curtain Control Panel product detail 2",
        type: "detail",
      },
    ],
  },
  "smart-four-key-scene-control-panel": {
    featuredImage: {
      src: "/media/products/smart-four-key-scene-control-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-four-key-scene-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Four-Key Scene Control Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-four-key-scene-control-panel/side-01.webp",
        thumbnailSrc: "/media/products/smart-four-key-scene-control-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Four-Key Scene Control Panel side view",
        type: "side",
      },
    ],
  },
  "smart-key-card-energy-saver-panel": {
    featuredImage: {
      src: "/media/products/smart-key-card-energy-saver-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-key-card-energy-saver-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Key Card Energy Saver Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-key-card-energy-saver-panel/detail-01.webp",
        thumbnailSrc: "/media/products/smart-key-card-energy-saver-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Key Card Energy Saver Panel product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/smart-key-card-energy-saver-panel/detail-02.webp",
        thumbnailSrc: "/media/products/smart-key-card-energy-saver-panel/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Key Card Energy Saver Panel product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/smart-key-card-energy-saver-panel/detail-03.webp",
        thumbnailSrc: "/media/products/smart-key-card-energy-saver-panel/thumb/detail-03.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Key Card Energy Saver Panel product detail 3",
        type: "detail",
      },
    ],
  },
  "smart-series-dual-vertical-socket-panel": {
    featuredImage: {
      src: "/media/products/smart-series-dual-vertical-socket-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-series-dual-vertical-socket-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Series Dual Vertical Socket Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-series-dual-vertical-socket-panel/side-01.webp",
        thumbnailSrc: "/media/products/smart-series-dual-vertical-socket-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Series Dual Vertical Socket Panel side view",
        type: "side",
      },
    ],
  },
  "smart-single-key-switch-panel": {
    featuredImage: {
      src: "/media/products/smart-single-key-switch-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-single-key-switch-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Single-Key Switch Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-single-key-switch-panel/side-01.webp",
        thumbnailSrc: "/media/products/smart-single-key-switch-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Single-Key Switch Panel side view",
        type: "side",
      },
    ],
  },
  "smart-three-key-music-control-panel": {
    featuredImage: {
      src: "/media/products/smart-three-key-music-control-panel/hero.webp",
      thumbnailSrc: "/media/products/smart-three-key-music-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Three-Key Music Control Panel",
    },
    gallery: [
      {
        src: "/media/products/smart-three-key-music-control-panel/side-01.webp",
        thumbnailSrc: "/media/products/smart-three-key-music-control-panel/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Three-Key Music Control Panel side view 1",
        type: "side",
      },
      {
        src: "/media/products/smart-three-key-music-control-panel/side-02.webp",
        thumbnailSrc: "/media/products/smart-three-key-music-control-panel/thumb/side-02.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Three-Key Music Control Panel side view 2",
        type: "side",
      },
    ],
  },
  "smart-usb-five-hole-socket": {
    featuredImage: {
      src: "/media/products/smart-usb-five-hole-socket/hero.webp",
      thumbnailSrc: "/media/products/smart-usb-five-hole-socket/thumb/hero.webp",
      width: 1200,
      height: 1200,
      alt: "Smart USB Five-Hole Socket",
    },
    gallery: [
      {
        src: "/media/products/smart-usb-five-hole-socket/detail-01.webp",
        thumbnailSrc: "/media/products/smart-usb-five-hole-socket/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart USB Five-Hole Socket product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/smart-usb-five-hole-socket/detail-02.webp",
        thumbnailSrc: "/media/products/smart-usb-five-hole-socket/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Smart USB Five-Hole Socket product detail 2",
        type: "detail",
      },
    ],
  },
  "smart-voice-telephone-information-socket": {
    featuredImage: {
      src: "/media/products/smart-voice-telephone-information-socket/hero.webp",
      thumbnailSrc: "/media/products/smart-voice-telephone-information-socket/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Smart Voice and Telephone Information Socket",
    },
    gallery: [
      {
        src: "/media/products/smart-voice-telephone-information-socket/side-01.webp",
        thumbnailSrc: "/media/products/smart-voice-telephone-information-socket/thumb/side-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Voice and Telephone Information Socket side view",
        type: "side",
      },
      {
        src: "/media/products/smart-voice-telephone-information-socket/back-01.webp",
        thumbnailSrc: "/media/products/smart-voice-telephone-information-socket/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Smart Voice and Telephone Information Socket back view",
        type: "back",
      },
    ],
  },
  "thermostat-hvac-control-panel": {
    featuredImage: {
      src: "/media/products/thermostat-hvac-control-panel/hero.webp",
      thumbnailSrc: "/media/products/thermostat-hvac-control-panel/thumb/hero.webp",
      width: 1200,
      height: 800,
      alt: "Thermostat HVAC Control Panel",
    },
    gallery: [
      {
        src: "/media/products/thermostat-hvac-control-panel/interface-01.webp",
        thumbnailSrc: "/media/products/thermostat-hvac-control-panel/thumb/interface-01.webp",
        width: 1600,
        height: 1066,
        alt: "Thermostat HVAC Control Panel interface detail",
        type: "interface",
      },
      {
        src: "/media/products/thermostat-hvac-control-panel/detail-01.webp",
        thumbnailSrc: "/media/products/thermostat-hvac-control-panel/thumb/detail-01.webp",
        width: 1600,
        height: 1066,
        alt: "Thermostat HVAC Control Panel product detail 1",
        type: "detail",
      },
      {
        src: "/media/products/thermostat-hvac-control-panel/detail-02.webp",
        thumbnailSrc: "/media/products/thermostat-hvac-control-panel/thumb/detail-02.webp",
        width: 1600,
        height: 1066,
        alt: "Thermostat HVAC Control Panel product detail 2",
        type: "detail",
      },
      {
        src: "/media/products/thermostat-hvac-control-panel/application-01.webp",
        thumbnailSrc: "/media/products/thermostat-hvac-control-panel/thumb/application-01.webp",
        width: 1600,
        height: 1066,
        alt: "Thermostat HVAC Control Panel application view",
        type: "application",
      },
    ],
  },
  "vintage-gold-four-key-smart-switch-panel": {
    featuredImage: {
      src: "/media/products/vintage-gold-four-key-smart-switch-panel/hero.webp",
      thumbnailSrc: "/media/products/vintage-gold-four-key-smart-switch-panel/thumb/hero.webp",
      width: 1181,
      height: 1200,
      alt: "Vintage Gold Four-Key Smart Switch Panel",
    },
    gallery: [
      {
        src: "/media/products/vintage-gold-four-key-smart-switch-panel/side-01.webp",
        thumbnailSrc: "/media/products/vintage-gold-four-key-smart-switch-panel/thumb/side-01.webp",
        width: 1506,
        height: 1600,
        alt: "Vintage Gold Four-Key Smart Switch Panel side view",
        type: "side",
      },
      {
        src: "/media/products/vintage-gold-four-key-smart-switch-panel/detail-01.webp",
        thumbnailSrc: "/media/products/vintage-gold-four-key-smart-switch-panel/thumb/detail-01.webp",
        width: 1437,
        height: 1600,
        alt: "Vintage Gold Four-Key Smart Switch Panel product detail",
        type: "detail",
      },
      {
        src: "/media/products/vintage-gold-four-key-smart-switch-panel/back-01.webp",
        thumbnailSrc: "/media/products/vintage-gold-four-key-smart-switch-panel/thumb/back-01.webp",
        width: 1537,
        height: 1554,
        alt: "Vintage Gold Four-Key Smart Switch Panel back view",
        type: "back",
      },
    ],
  },
  "vintage-gold-key-card-energy-saver-panel": {
    featuredImage: {
      src: "/media/products/vintage-gold-key-card-energy-saver-panel/hero.webp",
      thumbnailSrc: "/media/products/vintage-gold-key-card-energy-saver-panel/thumb/hero.webp",
      width: 1173,
      height: 1200,
      alt: "Vintage Gold Key Card Energy Saver Panel",
    },
    gallery: [
      {
        src: "/media/products/vintage-gold-key-card-energy-saver-panel/side-01.webp",
        thumbnailSrc: "/media/products/vintage-gold-key-card-energy-saver-panel/thumb/side-01.webp",
        width: 1515,
        height: 1412,
        alt: "Vintage Gold Key Card Energy Saver Panel side view",
        type: "side",
      },
      {
        src: "/media/products/vintage-gold-key-card-energy-saver-panel/back-01.webp",
        thumbnailSrc: "/media/products/vintage-gold-key-card-energy-saver-panel/thumb/back-01.webp",
        width: 1600,
        height: 1066,
        alt: "Vintage Gold Key Card Energy Saver Panel back view",
        type: "back",
      },
    ],
  },
};
