export const chineseAboutCopy = {
  heroEyebrow: "公司简介",
  profileEyebrow: "公司简介",
  profileTitle: "我们是谁",
  deliveryEyebrow: "交付模式",
  deliveryTitle: "从产品设计到合格生产",
  workflowEyebrow: "项目流程",
  workflowTitle: "从需求确认到项目支持的清晰路径",
  capabilityEyebrow: "解决方案能力",
  capabilityTitle: "酒店智能客房控制能力",
  capabilityDescription:
    "我们为完整的酒店客房控制方案和互联智能家居项目规划产品组合。",
  capabilities: [
    "RCU 客房控制主机",
    "AI 智能控制显示屏",
    "智能面板与开关",
    "传感器",
    "智能插座与电源模块",
    "窗帘控制",
    "HVAC 温控",
    "房态显示与酒店服务面板",
    "酒店配送机器人系统",
  ],
  customizationEyebrow: "定制",
  customizationTitle: "OEM/ODM 项目支持",
  customersEyebrow: "客户",
  customersTitle: "我们的合作对象",
  customerTypes: [
    "酒店业主",
    "酒店项目承包商",
    "系统集成商",
    "智能家居分销商",
    "工程公司",
    "OEM/ODM 合作伙伴",
  ],
  marketsEyebrow: "目标市场",
  marketsTitle: "中东与东南亚",
  marketsDescription:
    "我们的重点市场为中东和东南亚；对于能够明确核对产品与项目要求的其他地区，我们同样支持海外 B2B 酒店与智能家居项目。",
  commercialEyebrow: "商务条件",
  commercialTitle: "样品、起订量与交期",
  commercialItems: [
    "可提供样品用于评估。",
    "样品费用和运输费用由客户承担。",
    "标准产品通常不设固定最低起订量。需要新模具时，定制产品可能产生模具或定制费用；使用现有模具仅改变颜色时，不收取定制费。",
    "常规交付周期通常为 7–15 天，实际时间取决于产品、订单数量、定制范围和项目要求。",
  ],
  supportEyebrow: "技术支持",
  supportTitle: "项目与技术支持",
  inquiryEyebrow: "项目询盘",
  inquiryTitle: "讨论您的项目",
  inquiryDescription:
    "请向我们的 B2B 团队提供房型、关注产品、数量范围、定制需求和交付计划。",
  contactLabel: "联系我们",
  solutionsLabel: "查看解决方案",
  whatsappLabel: "通过 WhatsApp 获取报价",
  breadcrumbHome: "首页",
  breadcrumbAbout: "关于我们",
} as const;
export const chineseContactCopy = {
  eyebrow: "项目联系",
  salesLabel: "销售与报价",
  salesDescription: "询盘、报价、采购、订单及 OEM/ODM 合作",
  generalLabel: "一般联系",
  generalDescription: "一般联系、品牌咨询与合作",
  supportLabel: "技术支持",
  supportDescription: "售后、技术支持、安装与产品资料",
  whatsappDescription:
    "为产品清单、酒店项目和 OEM/ODM 需求提供快捷报价支持。",
  whatsappLabel: "通过 WhatsApp 获取报价",
  reviewEyebrow: "加快项目审核",
  reviewTitle: "请提供影响产品选型的关键信息",
  reviewItems: [
    ["项目范围", "国家或地区、酒店类型、房间数量、项目阶段和交付目标。"],
    ["技术匹配", "电压、频率、协议、布线、面板表面处理和客房功能。"],
    ["商务需求", "预计数量、OEM/ODM 范围、资料、样品和包装。"],
  ],
  detailsEyebrow: "联系方式",
  detailsTitle: "办公室地址、微信与电话",
  officeLabel: "办公室地址",
  wechatLabel: "微信号",
  phoneLabel: "电话",
  qrAlt: "DUALCORE LINK 联系微信二维码",
  qrHelp: "扫码添加微信联系人。",
  quoteTitle: "获取报价",
  quoteServerIntro:
    "将询盘资料安全提交给销售团队。如服务暂时不可用，请使用",
  quoteMailtoIntro: "将询盘资料发送给销售团队。本表单会打开邮件草稿并发送至",
  quoteHelp:
    "中东和东南亚项目请提供国家、酒店房型、电压与频率要求、协议偏好、预计数量和所需资料。",
  quoteSteps: [
    "提供项目简介和关注产品。",
    "我们核对技术匹配和资料需求。",
    "通过邮件或 WhatsApp 继续确认报价细节。",
  ],
} as const;

export const arabicAboutCopy = {
  heroEyebrow: "نبذة عن الشركة",
  profileEyebrow: "نبذة عن الشركة",
  profileTitle: "من نحن",
  deliveryEyebrow: "نموذج التسليم",
  deliveryTitle: "من تصميم المنتج إلى الإنتاج وفق المتطلبات المعتمدة",
  workflowEyebrow: "سير عمل المشروع",
  workflowTitle: "مسار واضح من المتطلبات إلى دعم المشروع",
  capabilityEyebrow: "قدرات الحلول",
  capabilityTitle: "قدرات التحكم في غرف الفنادق الذكية",
  capabilityDescription: "نخطط مجموعات من المنتجات لحلول التحكم في غرف الفنادق ومشروعات المنازل الذكية المتصلة.",
  capabilities: ["وحدات تحكم RCU", "شاشات التحكم الذكية", "اللوحات والمفاتيح الذكية", "المستشعرات", "المقابس ووحدات الطاقة", "الستائر", "HVAC والثرموستات", "حالة الغرفة وخدمات الفندق", "روبوتات التوصيل الفندقية"],
  customizationEyebrow: "التخصيص",
  customizationTitle: "دعم مشروعات OEM/ODM",
  customersEyebrow: "العملاء",
  customersTitle: "الجهات التي نعمل معها",
  customerTypes: ["مالكو الفنادق", "مقاولو المشروعات", "متكاملو الأنظمة", "موزعو المنازل الذكية", "الشركات الهندسية", "شركاء OEM/ODM"],
  marketsEyebrow: "الأسواق المستهدفة",
  marketsTitle: "الشرق الأوسط وجنوب شرق آسيا",
  marketsDescription: "نركز على الشرق الأوسط وجنوب شرق آسيا، وندعم مشروعات B2B في أسواق أخرى عندما يمكن مراجعة متطلبات المنتج والمشروع بوضوح.",
  commercialEyebrow: "الشروط التجارية",
  commercialTitle: "العينات وMOQ ومدة التسليم",
  commercialItems: ["تتوفر عينات للتقييم.", "يتحمل العميل تكلفة العينة والشحن.", "لا يوجد حد أدنى ثابت للمنتجات القياسية؛ وقد توجد رسوم قالب أو تخصيص عند الحاجة إلى قالب جديد، بينما لا يفرض تغيير اللون باستخدام قالب قائم رسوم تخصيص.", "مدة التسليم المعتادة 7–15 يوماً، وفق المنتج والكمية ونطاق التخصيص."],
  supportEyebrow: "الدعم الفني",
  supportTitle: "دعم المشروع والدعم الفني",
  inquiryEyebrow: "استفسار المشروع",
  inquiryTitle: "ناقش مشروعك",
  inquiryDescription: "شارك أنواع الغرف والمنتجات والكمية والتخصيص وخطة التسليم مع فريق B2B.",
  contactLabel: "اتصل بنا",
  solutionsLabel: "استكشف الحلول",
  whatsappLabel: "اطلب عرضاً عبر WhatsApp",
  breadcrumbHome: "الرئيسية",
  breadcrumbAbout: "من نحن",
} as const;

export const arabicContactCopy = {
  eyebrow: "استفسارات المشروعات",
  salesLabel: "المبيعات وعروض الأسعار",
  salesDescription: "الاستفسارات وعروض الأسعار والشراء والتعاون في مشروعات OEM/ODM",
  generalLabel: "اتصال عام",
  generalDescription: "التواصل العام والعلامة التجارية والتعاون",
  supportLabel: "الدعم الفني",
  supportDescription: "ما بعد البيع والدعم والتركيب ووثائق المنتجات",
  whatsappDescription: "دعم سريع لطلبات عروض الأسعار وقوائم المنتجات ومشروعات الفنادق وOEM/ODM.",
  whatsappLabel: "اطلب عرضاً عبر WhatsApp",
  reviewEyebrow: "مراجعة أسرع للمشروع",
  reviewTitle: "أرسل المعلومات التي تؤثر في اختيار المنتج",
  reviewItems: [["نطاق المشروع", "الدولة ونوع الفندق وعدد الغرف والمرحلة وموعد التسليم."], ["الملاءمة الفنية", "الجهد والتردد والبروتوكول والأسلاك وتشطيب اللوحة ووظائف الغرفة."], ["الاحتياجات التجارية", "الكمية ونطاق OEM/ODM والوثائق والعينات والتغليف."]],
  detailsEyebrow: "بيانات الاتصال",
  detailsTitle: "عنوان المكتب وWeChat والهاتف",
  officeLabel: "عنوان المكتب",
  wechatLabel: "معرف WeChat",
  phoneLabel: "الهاتف",
  qrAlt: "رمز QR للتواصل مع DUALCORE LINK عبر WeChat",
  qrHelp: "امسح الرمز لإضافة جهة الاتصال.",
  quoteTitle: "اطلب عرض سعر",
  quoteServerIntro: "أرسل بيانات الاستفسار بأمان إلى فريق المبيعات. إذا تعذر التسليم، استخدم",
  quoteMailtoIntro: "يفتح هذا النموذج مسودة بريد إلى",
  quoteHelp: "لمشروعات الشرق الأوسط وجنوب شرق آسيا، اذكر الدولة ونوع الغرفة والجهد والتردد والبروتوكول والكمية والوثائق المطلوبة.",
  quoteSteps: ["شارك ملخص المشروع والمنتجات المطلوبة.", "نراجع الملاءمة الفنية والوثائق.", "تابع عبر البريد أو WhatsApp لتفاصيل العرض."],
} as const;

export const vietnameseAboutCopy = {
  heroEyebrow: "Hồ sơ doanh nghiệp",
  profileEyebrow: "Giới thiệu doanh nghiệp",
  profileTitle: "Chúng tôi là ai",
  deliveryEyebrow: "Mô hình cung ứng",
  deliveryTitle: "Từ thiết kế sản phẩm đến sản xuất theo yêu cầu đã duyệt",
  workflowEyebrow: "Quy trình dự án",
  workflowTitle: "Lộ trình rõ ràng từ xác nhận yêu cầu đến hỗ trợ dự án",
  capabilityEyebrow: "Năng lực giải pháp",
  capabilityTitle: "Năng lực điều khiển phòng khách sạn thông minh",
  capabilityDescription:
    "Chúng tôi lập kế hoạch danh mục sản phẩm cho giải pháp điều khiển phòng khách sạn và dự án nhà thông minh kết nối.",
  capabilities: [
    "Bộ điều khiển phòng RCU",
    "Màn hình điều khiển thông minh AI",
    "Bảng điều khiển và công tắc thông minh",
    "Cảm biến",
    "Ổ cắm thông minh và mô-đun nguồn",
    "Điều khiển rèm",
    "Điều khiển HVAC và bộ điều nhiệt",
    "Bảng trạng thái phòng và dịch vụ khách sạn",
    "Hệ thống robot giao hàng khách sạn",
  ],
  customizationEyebrow: "Tùy chỉnh",
  customizationTitle: "Hỗ trợ dự án OEM/ODM",
  customersEyebrow: "Khách hàng",
  customersTitle: "Đối tác chúng tôi phục vụ",
  customerTypes: [
    "Chủ đầu tư khách sạn",
    "Nhà thầu dự án khách sạn",
    "Đơn vị tích hợp hệ thống",
    "Nhà phân phối nhà thông minh",
    "Công ty kỹ thuật",
    "Đối tác OEM/ODM",
  ],
  marketsEyebrow: "Thị trường mục tiêu",
  marketsTitle: "Trung Đông và Đông Nam Á",
  marketsDescription:
    "Chúng tôi tập trung vào Trung Đông và Đông Nam Á, đồng thời hỗ trợ dự án B2B tại các thị trường khác khi có thể xác nhận rõ yêu cầu sản phẩm và dự án.",
  commercialEyebrow: "Điều kiện thương mại",
  commercialTitle: "Mẫu, MOQ và thời gian giao hàng",
  commercialItems: [
    "Có thể cung cấp mẫu để đánh giá.",
    "Khách hàng chịu chi phí mẫu và vận chuyển.",
    "Sản phẩm tiêu chuẩn thường không có MOQ cố định. Sản phẩm tùy chỉnh có thể phát sinh phí khuôn hoặc phí tùy chỉnh khi cần khuôn mới; đổi màu trên khuôn hiện có không tính phí tùy chỉnh.",
    "Thời gian giao hàng thông thường là 7–15 ngày, tùy sản phẩm, số lượng, phạm vi tùy chỉnh và yêu cầu dự án.",
  ],
  supportEyebrow: "Hỗ trợ kỹ thuật",
  supportTitle: "Hỗ trợ dự án và kỹ thuật",
  inquiryEyebrow: "Yêu cầu dự án",
  inquiryTitle: "Trao đổi về dự án của bạn",
  inquiryDescription:
    "Hãy gửi loại phòng, sản phẩm quan tâm, số lượng, yêu cầu tùy chỉnh và kế hoạch giao hàng cho đội ngũ B2B.",
  contactLabel: "Liên hệ",
  solutionsLabel: "Xem giải pháp",
  whatsappLabel: "Yêu cầu báo giá qua WhatsApp",
  breadcrumbHome: "Trang chủ",
  breadcrumbAbout: "Giới thiệu",
} as const;

export const vietnameseContactCopy = {
  eyebrow: "Liên hệ dự án",
  salesLabel: "Kinh doanh và báo giá",
  salesDescription: "Yêu cầu, báo giá, mua hàng, đơn hàng và hợp tác OEM/ODM",
  generalLabel: "Liên hệ chung",
  generalDescription: "Trao đổi chung, thương hiệu và hợp tác",
  supportLabel: "Hỗ trợ kỹ thuật",
  supportDescription: "Hậu mãi, hỗ trợ kỹ thuật, lắp đặt và tài liệu sản phẩm",
  whatsappDescription:
    "Hỗ trợ nhanh cho danh mục sản phẩm, dự án khách sạn và yêu cầu OEM/ODM.",
  whatsappLabel: "Yêu cầu báo giá qua WhatsApp",
  reviewEyebrow: "Rút ngắn thời gian rà soát",
  reviewTitle: "Cung cấp thông tin ảnh hưởng đến việc lựa chọn sản phẩm",
  reviewItems: [
    ["Phạm vi dự án", "Quốc gia hoặc khu vực, loại khách sạn, số phòng, giai đoạn và mục tiêu giao hàng."],
    ["Phù hợp kỹ thuật", "Điện áp, tần số, giao thức, dây dẫn, bề mặt bảng điều khiển và chức năng phòng."],
    ["Yêu cầu thương mại", "Số lượng dự kiến, phạm vi OEM/ODM, tài liệu, mẫu và bao bì."],
  ],
  detailsEyebrow: "Thông tin liên hệ",
  detailsTitle: "Địa chỉ văn phòng, WeChat và điện thoại",
  officeLabel: "Địa chỉ văn phòng",
  wechatLabel: "WeChat",
  phoneLabel: "Điện thoại",
  qrAlt: "Mã QR WeChat liên hệ DUALCORE LINK",
  qrHelp: "Quét mã để thêm liên hệ WeChat.",
  quoteTitle: "Yêu cầu báo giá",
  quoteServerIntro:
    "Gửi thông tin yêu cầu một cách an toàn đến đội ngũ kinh doanh. Nếu dịch vụ tạm thời không khả dụng, hãy dùng",
  quoteMailtoIntro: "Biểu mẫu này mở bản nháp email gửi đến",
  quoteHelp:
    "Với dự án tại Trung Đông và Đông Nam Á, hãy cung cấp quốc gia, loại phòng, điện áp và tần số, giao thức ưu tiên, số lượng dự kiến và tài liệu cần thiết.",
  quoteSteps: [
    "Cung cấp tóm tắt dự án và sản phẩm quan tâm.",
    "Chúng tôi kiểm tra tính phù hợp kỹ thuật và nhu cầu tài liệu.",
    "Tiếp tục xác nhận báo giá qua email hoặc WhatsApp.",
  ],
} as const;
