export const chineseAboutCopy = {
  heroEyebrow: "公司简介",
  profileEyebrow: "公司简介",
  profileTitle: "我们是谁",
  deliveryEyebrow: "交付模式",
  deliveryTitle: "从产品设计到合格生产",
  workflowEyebrow: "项目流程",
  workflowTitle: "从需求确认到项目支持的清晰路径",
  capabilityEyebrow: "解决方案能力",
  capabilityTitle: "酒店智能客房控制能力",
  capabilityDescription:
    "我们为完整的酒店客房控制方案和互联智能家居项目规划产品组合。",
  capabilities: [
    "RCU 客房控制主机",
    "AI 智能控制显示屏",
    "智能面板与开关",
    "传感器",
    "智能插座与电源模块",
    "窗帘控制",
    "HVAC 温控",
    "房态显示与酒店服务面板",
    "酒店配送机器人系统",
  ],
  customizationEyebrow: "定制",
  customizationTitle: "OEM/ODM 项目支持",
  customersEyebrow: "客户",
  customersTitle: "我们的合作对象",
  customerTypes: [
    "酒店业主",
    "酒店项目承包商",
    "系统集成商",
    "智能家居分销商",
    "工程公司",
    "OEM/ODM 合作伙伴",
  ],
  marketsEyebrow: "目标市场",
  marketsTitle: "中东与东南亚",
  marketsDescription:
    "我们的重点市场为中东和东南亚；对于能够明确核对产品与项目要求的其他地区，我们同样支持海外 B2B 酒店与智能家居项目。",
  commercialEyebrow: "商务条件",
  commercialTitle: "样品、起订量与交期",
  commercialItems: [
    "可提供样品用于评估。",
    "样品费用和运输费用由客户承担。",
    "标准产品通常不设固定最低起订量。需要新模具时，定制产品可能产生模具或定制费用；使用现有模具仅改变颜色时，不收取定制费。",
    "常规交付周期通常为 7–15 天，实际时间取决于产品、订单数量、定制范围和项目要求。",
  ],
  supportEyebrow: "技术支持",
  supportTitle: "项目与技术支持",
  inquiryEyebrow: "项目询盘",
  inquiryTitle: "讨论您的项目",
  inquiryDescription:
    "请向我们的 B2B 团队提供房型、关注产品、数量范围、定制需求和交付计划。",
  contactLabel: "联系我们",
  solutionsLabel: "查看解决方案",
  whatsappLabel: "通过 WhatsApp 获取报价",
  breadcrumbHome: "首页",
  breadcrumbAbout: "关于我们",
} as const;
export const chineseContactCopy = {
  eyebrow: "项目联系",
  salesLabel: "销售与报价",
  salesDescription: "询盘、报价、采购、订单及 OEM/ODM 合作",
  generalLabel: "一般联系",
  generalDescription: "一般联系、品牌咨询与合作",
  supportLabel: "技术支持",
  supportDescription: "售后、技术支持、安装与产品资料",
  whatsappDescription:
    "为产品清单、酒店项目和 OEM/ODM 需求提供快捷报价支持。",
  whatsappLabel: "通过 WhatsApp 获取报价",
  reviewEyebrow: "加快项目审核",
  reviewTitle: "请提供影响产品选型的关键信息",
  reviewItems: [
    ["项目范围", "国家或地区、酒店类型、房间数量、项目阶段和交付目标。"],
    ["技术匹配", "电压、频率、协议、布线、面板表面处理和客房功能。"],
    ["商务需求", "预计数量、OEM/ODM 范围、资料、样品和包装。"],
  ],
  detailsEyebrow: "联系方式",
  detailsTitle: "办公室地址、微信与电话",
  officeLabel: "办公室地址",
  wechatLabel: "微信号",
  phoneLabel: "电话",
  qrAlt: "DUALCORE LINK 联系微信二维码",
  qrHelp: "扫码添加微信联系人。",
  quoteTitle: "获取报价",
  quoteServerIntro:
    "将询盘资料安全提交给销售团队。如服务暂时不可用，请使用",
  quoteMailtoIntro: "将询盘资料发送给销售团队。本表单会打开邮件草稿并发送至",
  quoteHelp:
    "中东和东南亚项目请提供国家、酒店房型、电压与频率要求、协议偏好、预计数量和所需资料。",
  quoteSteps: [
    "提供项目简介和关注产品。",
    "我们核对技术匹配和资料需求。",
    "通过邮件或 WhatsApp 继续确认报价细节。",
  ],
} as const;
